# Site Settings
title                    : "Zhangding Liu"
description              : "Ph.D. Student at Georgia Tech"
repository               : "ZhangdingLiu/ZhangdingLiu.github.io"
google_scholar_stats_use_cdn : true

# google analytics
google_analytics_id      :  # optional

# SEO Related
google_site_verification :  
bing_site_verification   :  
baidu_site_verification  :  

# Site Author
author:
  name             : "Zhangding Liu"
  avatar           : "images/avatar.jpg"
  bio              : "Ph.D. Student in Civil Engineering (Minor in CS), M.S. in Computational Science and Engineering"
  location         : "Atlanta, Georgia"
  employer         : "Georgia Institute of Technology"
  pubmed           : 
  googlescholar    : "https://scholar.google.com/citations?user=XXXXXX"  # ← 你可以填上你自己的 Scholar 链接
  email            : "zliu952@gatech.edu"
  researchgate     : 
  uri              :
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : "ZhangdingLiu"
  google_plus      :
  keybase          :
  instagram        :
  impactstory      : 
  lastfm           :
  linkedin         : zhangdingliu  # ← 如果你有 LinkedIn 可填 username
  dblp             : 
  orcid            : 
  pinterest        :
  soundcloud       :
  stackoverflow    : 
  steam            :
  tumblr           :
  twitter          : "@ZhangdingLiu"  # 如果你没有 Twitter 可以删掉这一行
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        :

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - docs
  - google_scholar_crawler
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .github
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: America/New_York

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
